# BlockReports Configuration
# A plugin to prevent chat reporting on Paper 1.21.6

# Enable debug logging
enable-logging: true

# Strip chat signatures from outgoing chat packets
# This converts signed chat messages to unsigned system messages
strip-chat-signatures: true

# Hide the secure chat warning popup
# This modifies server data packets to prevent the client from showing warnings
hide-secure-chat-warning: true

# ============================================================================
# IMPORTANT NOTES:
# ============================================================================
# 
# This plugin uses PacketEvents to intercept and modify chat packets at the
# protocol level for maximum effectiveness. It:
#
# 1. Converts signed player chat messages to unsigned system messages
# 2. Cancels chat header packets that contain signature metadata  
# 3. Modifies server data to hide secure chat warnings
#
# This provides comprehensive protection against chat reporting without
# requiring server.properties changes, though setting 
# enforce-secure-profile=false is still recommended.
# ============================================================================ 