name: BlockReports
version: '1.0'
main: com.jellypudding.blockReports.BlockReports
api-version: '1.21'
author: AlphaAlex115
description: Blocks Minecraft chat reporting by stripping signatures, hiding warning popups, and preventing signature-based kicks.
website: www.minecraftoffline.net

commands:
  blockreports:
    description: "BlockReports management commands"
    usage: "/blockreports reload"
    aliases: [br]

permissions:
  blockreports.admin:
    description: "Allows use of BlockReports commands"
    default: op