name: BlockReports
version: '1.0-SNAPSHOT'
main: com.jellypudding.blockReports.BlockReports
api-version: '1.21'
author: AlphaAlex115
description: Prevents chat reporting by stripping message signatures and enforcing server-side protection.
website: wwww.minecraftoffline.net

commands:
  blockreports:
    description: "BlockReports management commands"
    usage: "/blockreports reload"
    aliases: [br]

permissions:
  blockreports.admin:
    description: "Allows use of BlockReports commands"
    default: op